name: Release Node.js app

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: zwenkka/practice

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v4         

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show image name being built
        run: echo "Will build $IMAGE_NAME:latest"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3       
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  

      - name: Build and push Docker image
        uses: docker/build-push-action@v6 
        with:
          context: ./express-app
          file: ./express-app/Dockerfile
          push: true
          platforms: linux/amd64      
          tags: zwenkka/practice:latest
